services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - hoteljulia_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      
  app:
    image: hoteljulia
    container_name: hoteljulia-app
    build:
      context: .
      args:
        JAR_NAME: hoteljulia-1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - hoteljulia_network
    depends_on:
      - db

volumes:
  pgdata:
    name: hoteljulia_pgdata

networks:
  hoteljulia_network:
    name: hoteljulia_network
    driver: bridge